// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWcRRDchwE11FIiIrrGU_MdwnbmvWoI1Y',
    appId: '1:216932429508:web:efe50f5c9a7e9d6b742391',
    messagingSenderId: '216932429508',
    projectId: 'app-gestion-finance-perso',
    authDomain: 'app-gestion-finance-perso.firebaseapp.com',
    storageBucket: 'app-gestion-finance-perso.firebasestorage.app',
    measurementId: 'G-HDMY28PHBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwc03dpuh1rc1EgZyRcDpCaeftpbN2LZE',
    appId: '1:216932429508:android:dbbd272eb939da6b742391',
    messagingSenderId: '216932429508',
    projectId: 'app-gestion-finance-perso',
    storageBucket: 'app-gestion-finance-perso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkulluxYTE-Nr4U0-HcK7Fy232yRHUYVk',
    appId: '1:216932429508:ios:197649d75c932943742391',
    messagingSenderId: '216932429508',
    projectId: 'app-gestion-finance-perso',
    storageBucket: 'app-gestion-finance-perso.firebasestorage.app',
    iosBundleId: 'com.example.appFinancePerso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkulluxYTE-Nr4U0-HcK7Fy232yRHUYVk',
    appId: '1:216932429508:ios:197649d75c932943742391',
    messagingSenderId: '216932429508',
    projectId: 'app-gestion-finance-perso',
    storageBucket: 'app-gestion-finance-perso.firebasestorage.app',
    iosBundleId: 'com.example.appFinancePerso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWcRRDchwE11FIiIrrGU_MdwnbmvWoI1Y',
    appId: '1:216932429508:web:140e45c75c4c400c742391',
    messagingSenderId: '216932429508',
    projectId: 'app-gestion-finance-perso',
    authDomain: 'app-gestion-finance-perso.firebaseapp.com',
    storageBucket: 'app-gestion-finance-perso.firebasestorage.app',
    measurementId: 'G-MXP45XSE35',
  );

}